version: 2.0
jobs:
  job-1:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
          name: The First Step
          command: |
            gradle test
      - store_test_results:
          path: build/test-results
  job-2: 
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run: 
          name: Create jar
          command: |
            gradle jar      
      - store_artifacts:
          path: build/libs
          destination: prefix
workflows: 
  version: 2
  two_jobs_flow:
    jobs: 
      - job-1
      - job-2:
          requires: 
            - job-1
