version: 2.0
jobs:
  dockerize:
    machine: true
    steps: 
      - checkout:
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      #Build the application image
      - run: docker build -t $DOCKER_USER/gilded:$CIRCLE_SHA1 .

      #deploy the image
      - run: docker push $DOCKER_USER/gilded:$CIRCLE_SHA1
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
          name: The First Step
          command: |
            gradle test
      - store_test_results:
          path: build/test-results
  package: 
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run: 
          name: Create jar
          command: |
            gradle jar      
      - store_artifacts:
          path: build/libs
          destination: prefix
workflows: 
  version: 2
  two_jobs_flow:
    jobs: 
      - test
      - package:
          requires: 
            - test
      - dockerize:
          requires:
            - package
